DROP TABLE IF EXISTS exercises CASCADE;
DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE exercises (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  instructions TEXT,
  gifUrl VARCHAR(255) NOT NULL
  url VARCHAR(255) NOT NULL
);

CREATE TABLE recipes (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  label VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL
);

CREATE TABLE workout_plan
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  owner_name VARCHAR(255) REFERENCES users(name) ON DELETE CASCADE,
  exercise_id INTEGER REFERENCES exercise(id) ON DELETE CASCADE,
  exercise_title VARCHAR(255) REFERENCES exercise(title) ON DELETE CASCADE,
  exercise_url VARCHAR(255) REFERENCES exercise(url) ON DELETE CASCADE,
  recipes_id INTEGER REFERENCES recipes(id) ON DELETE CASCADE,
  recipes_label VARCHAR(255) REFERENCES recipes(label) ON DELETE CASCADE,
  recipe_url VARCHAR(255) REFERENCES recipe(url) ON DELETE CASCADE,